# Generated by Django 5.1.5 on 2025-02-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="desserts/user_pics/default.png", upload_to="desserts/user_pics"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
