# Generated by Django 5.1.5 on 2025-02-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_alter_user_options_user_photo_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
