# Generated by Django 5.1.5 on 2025-03-17 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="desserts/profile.pics"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=300, verbose_name="about"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
