# Generated by Django 5.1.5 on 2025-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "my_auth",
            "0003_alter_user_options_remove_user_bio_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="*Write something sweet or funny about desserts. This text will be displayed publicly on the 'Dessert Buddies' page.",
                max_length=300,
                verbose_name="about",
            ),
        ),
    ]
