# Generated by Django 5.1.5 on 2025-02-03 00:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CakeByDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_design", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CakeByFlavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_flavour", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CakeByOccasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "by_occasion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "cake_by_design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cakebydesign",
                    ),
                ),
                (
                    "cake_by_flavour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cakebyflavour",
                    ),
                ),
                (
                    "cake_by_occasion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cakebyoccasion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cake",
                "verbose_name_plural": "Cakes",
            },
        ),
    ]
