# Generated by Django 5.1.5 on 2025-02-03 02:09

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CakePop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cake_pops", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField(blank=True, default=1)),
            ],
            options={
                "verbose_name_plural": "Cake Pops",
            },
        ),
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cocktail_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
                (
                    "recipe",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cocktail",
                "verbose_name_plural": "Cocktails",
            },
        ),
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookie", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    tinymce.models.HTMLField(
                        default="", max_length=4096, verbose_name="Description"
                    ),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField(blank=True, default=1)),
            ],
            options={
                "verbose_name": "Cookie",
                "verbose_name_plural": "Cookies",
            },
        ),
        migrations.AddField(
            model_name="cake",
            name="quantity",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.FloatField(blank=True, default=0, null=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline"
                    ),
                ),
                (
                    "cake",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cake",
                    ),
                ),
                (
                    "cake_pops",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cakepop",
                    ),
                ),
                (
                    "cookie",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desserts.cookie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
