# Generated by Django 5.1.5 on 2025-03-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "New"),
                    ("P", "In Progress"),
                    ("C", "Completed"),
                    ("D", "Delivered"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
