# Generated by Django 5.1.5 on 2025-02-03 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0002_cakepop_cocktail_cookie_cake_quantity_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cake",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.cake",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cake_pops",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.cakepop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cookie",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.cookie",
            ),
        ),
    ]
