# Generated by Django 5.1.5 on 2025-02-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.category",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.order",
            ),
        ),
    ]
