# Generated by Django 5.1.5 on 2025-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deadline",
            field=models.DateTimeField(null=True, verbose_name="Deadline"),
        ),
    ]
