# Generated by Django 5.1.5 on 2025-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0003_alter_order_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="options",
            field=models.ManyToManyField(
                help_text="*To select more than one Option, press CTRL and left mouse key. Choose a dessert flavor.",
                to="desserts.option",
            ),
        ),
    ]
