# Generated by Django 5.1.5 on 2025-02-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0003_remove_orderline_product_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.category",
            ),
        ),
    ]
