# Generated by Django 5.1.5 on 2025-02-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0004_orderline_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="order",
        ),
    ]
