# Generated by Django 5.1.5 on 2025-02-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0005_remove_orderline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "New"),
                    ("P", "In Progress"),
                    ("C", "Completed"),
                    ("D", "Delivered"),
                ],
                default="NEW",
                max_length=1,
            ),
        ),
    ]
