# Generated by Django 5.1.5 on 2025-02-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0006_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.product",
            ),
        ),
    ]
