# Generated by Django 5.1.5 on 2025-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0009_remove_order_total_price_alter_orderline_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
