# Generated by Django 5.1.5 on 2025-03-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0010_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="desserts.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="options",
            field=models.ManyToManyField(
                help_text="*To select more than one Option, press CTRL and left mouse key.",
                to="desserts.option",
            ),
        ),
    ]
