# Generated by Django 5.1.5 on 2025-03-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0011_option_product_alter_orderline_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="product",
        ),
    ]
