# Generated by Django 5.1.5 on 2025-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0012_remove_option_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery")),
                (
                    "image_category",
                    models.CharField(
                        choices=[
                            ("index", "Homepage"),
                            ("cakes", "Cakes Page"),
                            ("cookies", "Cookies Page"),
                            ("cake_pops", "Cake Pops"),
                        ],
                        default="index",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
