# Generated by Django 5.1.5 on 2025-03-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0014_gallerycategory_alter_galleryimage_image_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.product",
            ),
        ),
    ]
