# Generated by Django 5.1.5 on 2025-03-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0015_galleryimage_name_alter_orderline_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="options",
            field=models.ManyToManyField(blank=True, null=True, to="desserts.option"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_line",
                to="desserts.product",
            ),
        ),
    ]
