# Generated by Django 5.1.5 on 2025-03-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0018_contacts_alter_productrating_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
    ]
