# Generated by Django 5.1.5 on 2025-03-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0019_rename_contacts_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="options",
            field=models.ManyToManyField(
                help_text="*To select more than one Option, press CTRL and left mouse key.",
                to="desserts.option",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="desserts.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.DeleteModel(
            name="OrderLine",
        ),
    ]
