# Generated by Django 5.1.5 on 2025-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desserts", "0020_order_options_order_product_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="options",
            field=models.ManyToManyField(blank=True, to="desserts.option"),
        ),
    ]
